/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as BlogHaberlerSlugRouteImport } from './routes/blog.haberler.$slug'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogHaberlerSlugRoute = BlogHaberlerSlugRouteImport.update({
  id: '/blog/haberler/$slug',
  path: '/blog/haberler/$slug',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/blog/haberler/$slug': typeof BlogHaberlerSlugRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/blog/haberler/$slug': typeof BlogHaberlerSlugRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/blog/haberler/$slug': typeof BlogHaberlerSlugRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/blog/haberler/$slug'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/blog/haberler/$slug'
  id: '__root__' | '/' | '/blog/haberler/$slug'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BlogHaberlerSlugRoute: typeof BlogHaberlerSlugRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/haberler/$slug': {
      id: '/blog/haberler/$slug'
      path: '/blog/haberler/$slug'
      fullPath: '/blog/haberler/$slug'
      preLoaderRoute: typeof BlogHaberlerSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BlogHaberlerSlugRoute: BlogHaberlerSlugRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
